= Datapages -- synchronizing json-style data
:toc: 
:toclevels: 4
:sectnums:
:sectnumlevels: 5
:source-highlighter: highlightjs

_Everything should be made as simple as possible, but not simpler_ -- http://quoteinvestigator.com/2011/05/13/einstein-simple/[Einstein]

Features:

* Very fast for small datasets (thousands of records)
* Data records are JSON-compatible JavaScript objects
* Objects can refer to each other naturally (like `alice.mother.mother.age`, cycles are okay)
* Instances can be linked into a federation (eg between web client and web server), with efficient propagation
* Easy to build live displays of dynamically-changing query results (no
polling)
* Change (delta) log is available for displaying history and provenance
* (TODO) Supports temporal and provenance features (only show data resulting from sources a and b before time t)
* (TODO) Supports transient records, aka event streaming
* (TODO) Supports access control for use in multiuser backends
* (TODO) Works with https://github.com/sandhawke/vocabspec[vocabspec] or https://github.com/sandhawke/data-sentence[data sentence]
to handle
schema validation, migration (with views), and integration
* (TODO) Supports streaming attached media blobs, eg JPEGs

== Design Concepts

=== Pages

We imagine a world full of "pages" of data, where each page is a
collection of properties with values, as might be serialized in JSON.
Pages are somewhat like documents in CouchDB or MongoDB, or rows in
a database table, or structs in C, or JSON Web Resources (which is
where the name comes from).  The values of properties may
be numbers, strings, booleans, timestamps, references to other pages,
or arrays of any of these.  We can create a page like this:

[source,javascript]
----
include::examples/dogs/fluffy.js[lines=5..12]
----

In that example, there are two nested objects, one about Hagrid and
one about the weakness of having music induce sleep.  Each of these is
a first class object, so this create() call will actually create three
objects, with the Fluffy page having references to the other two. In
practice, we would probably want to fill them in with more details
about Hagrid to be clear who we are talking about, or use a reference
to an existing page about Hagrid.

=== Views

An API user interacts with the world of pages by creating one or more
"views".  Within a given view, only a subset of the possible pages
will appear.  Views are somewhat similar to queries in general, but
more like SQL views, in that they are long lasting: as pages change,
the view changes.  They are a bit like collections in MongoDB, except
that a page can appear in many views or no views, depending how the
specific views are defined.  We can create a view like this:

[source,javascript]
----
include::examples/dogs/watch.js[lines=5..12]
----

This view will gather and make available pages which have an isDog
property with the value true and which have name and breed properties
defined and non-null.  When working with a view like this, one can
trust that these conditions will be met, with name and breed
properties available in memory.

We consider the world to be in a state of flux, with pages changing in
various places, and those changes propagating, both within the
application process, and across an unreliable network.  When you
create a view, it starts empty but begins to be filled by matching
pages. Some of that filling will happen immediately, using data
already in memory, but it may proceed with data coming in over the
network or from storage devices.  There is (usually) no distinction
between new pages appearing in the view because a disk read completed
and because a user clicked and changed a value.

Given this state of flux, much of the API is based around events, so
code like this is common:

[source,javascript]
----
include::examples/dogs/watch.js[lines=13..100]
----

=== Advanced Topics

==== Deltas

TBD

==== Semantics

mostly TBD

We consider each page to be expressing some knowledge about a
particular conceptual entity, its "subject", and some places in the
API we call the page "subject".

== Standard methods on a db (database view)

The 'ondurable' argument is always optional and is mostly useful for
UI operations, giving the user feedback that it's completed.  We could
use promises.   (Is that efficient when it's usually ignored?)

=== db.create(obj)

Creates a new page in db.  Immediately returns a handle for that page.

Providing an object is shorthand for create + overlay, but you don't
get the promise returned by overlay.

=== db.setProperty(subject, property, value, who, when, why)

Sets the given property of the given subject page to have the given value.

Args who, when, and why are optional and rarely used.  See Deltas for
details of their use.

Returns a promise (safe to ignore) which resolves when the change has
become durable.

=== subj.prop = val    [proxy]

Shorthand for `db.setProperty(subj, prop, val)`

=== db.overlay(page, overlay)

Call setProperty(page, property, value) for each key-value pair in overlay

Returns a promise (safe to ignore) which resolves when the change has
become durable.

=== db.delete(page)

Mark the page as deleted.  It will 'disappear' as appropriate.  This
is just another change, though, and subject to the usual delta
management.  Actually implemented as setProperty(page, '_deleted',
true).

Return a promise (safe to ignore) which resolves whe the change has
become durable.

ISSUE: can you undelete?

=== db.getProperty(page, prop) [proxy]

Returns the value, if immediately available, otherwise `undefined`

=== page.prop [proxy]

Shorthand for `db.getProperty(page, prop)`

=== db.waitForProperty(page, prop, timeout)  [proxy]

Returns a Promise which resolves when a value for page.prop is found,
or `undefined` after `timeout` milliseconds (default 2000).  If `timeout` is null, waits forever.  If `timeout` is 0,
equivalent to `db.getProperty()`.

=== db.on / db.off / db.once

Request to have a function called when database state changes.
Details are below in the list of events.  Probably implemented with
EventEmitter3, but use of methods other than .on .off and .once is not
supported.

=== db.replaySince(seq, event, cb)

Like db.on, but for events in the past, start at `delta.seq` equal to
`seq`.

Do no use db.replaceSince and then call db.on, unless you're fine with
dropping events.  Use db.listenSince to make a seamless transition.

=== db.listenSince(seq, event, cb)

A combination of `db.replaySince` and `db.on` guaranteed to give all
the events, in order, starting with `seq` and proceeding into the
future.

=== db.view(viewOptions)

Create and return a view of this db using the given options.  See
Views for details.

=== db.bridge(otherDB)

Initiates bridging between these two dbs, bringing them into sync.

Return a Bridge object to control it.

=== db.close()

Close the db and release resources.  This may be necessary for a
nodejs client to terminate, since an open network connection keeps the
process alive.

Returns an ignorable Promise which resolves when lower levels report
completion.  Worth waiting for during repeated testing, at least.

== Database Classes

=== datapages.InMem()

Straightforward in-memory DB, using JavaScript Proxy objects.  Supports full api, including features tagged "[proxy]"

=== [TODO] datapages-pg.PG

Integrate pg-live-data

=== datapages.MinDB()

Straightforward in-memory delta-only DB.  Does not support items tagged "[proxy]".

=== datapages.FlatFile(filename)

On-disk delta-only DB.

=== datapages.Remote

Full-featured (including Proxies) connection to a server.  Implemented
as InMem bridged to RawClient.

=== datapages.RawClient

Delta-only connection to server.

== Views

When a view is constructed, several properties can be specified,
defining the view.  Every view has one 'base' db, which it present
pages selected from.

=== name

TBD

=== filter

TBD

=== groupBy

TBD

=== [TODO] sortBy

If a db is ordered, then .limit makes a lot more sense.

On a sorted view, you can also do: db.first(), db.last(), db.index(0),
db.index(-1), etc.

=== [TODO] limit

Aka db.slice(0, n-1)

=== [TODO] deltaFilter

TBD

== Events

=== Event: appear

Emitted when a new page appears in the dbview, passed that page.
Optional addition parameter is the delta which triggered the event.

Note that watching for `appear` on a top level db will get you lots of
empty objects, because they appear before their properties.  So this
is mostly useful on views where the desired properties have been
flagged as `required`.

=== Event: disappear

Emitted when a page goes away from the dbview, passed that page.
Optional addition parameter is the delta which triggered the event.

=== Event: stable

Emitted when no changes have occured for `stabilityms` milliseconds.
Useful for browser displays.

=== Event: change

Emitted whenever anything changes, possibly several times per change.
Called with the page and the delta.  Don't update a display with every
change; either use it to set a dirty bit, or use the 'stable' event,
depending whether you want the display to have lots of fast motion.

=== Event: delta

Similar the `change`, but only passes the delta.  Mostly used internally.

=== [TODO] Event: error

Some asynchronous error has occured.  Passed an object with .message
and .code, where .code is listed under [Errors].

=== [TODO] Event: results

Emitted the same time as 'stable', but given an Array containing a
frozen copy of the current db.  Producing and/or maintaining that copy
might be expensive, so us 'stable' unless you're actually going to use
that parameter.

=== [TODO] Event: progress

Emitted with (stepsDone, totalSteps), at least once per second during
long operations.  stepsDone will always increase (unless things are
restarted), but totalSteps might also, so the fraction complete
(stepsDone / totalSteps) might decrease.  When stepsDone ===
totalSteps, we should be 'stable'.

== Merge

TBD
