= Older API Bits, mostly interesting ideas
:toc: 
:toclevels: 4
:sectnums:
:sectnumlevels: 5
:source-highlighter: highlightjs

== ...

=== [IDEA] Event: update-*

'update-before' is called with (page, overlay), where the overlay is
relative to some previous state that the receiver might not have, and
a reference object, such as one would pass as the first argument on
update.  For some situations, like event is sufficient.  Might be
called when the overlay actually changes no data, unlike the other
update-* events.

'update-full' is called with (before, after, overlay).  This is
somewhat more expensive to create, so if update-light is good enough,
use that.

'update-after' is called with (ref, overlay), where the overlay has
been applied

'update-property is called with (property, value-before, value-after,
ref).  If you only care about one property, you can hook into this and
quickly check if the property is the one you want.

=== db.count()

=== db.lookup(itemref, property) or (itemref, filter-expr)

a shortcut for a filter that selects that one item, and optionally
produces that one property of the item, or the item only when it
matches that filter.  Often followed by .once('results', ...) to see
the value if/when it appears, or .on('results', ...) to also see when
it changes.

=== [IDEA] db.select(arrayOfPropertyNames)   aka db.project(...)

A performance hint, telling the underlying system that it's safe to
ignore all properties not in the given list.  That is, it returns a
dbview where no effort is made to report the values of properties not
in this list.  Could be read as "properties I care about".

If your on-appear listener only looks at three properties, then it's good to put a .select() for those three properties before the .on(), so no effort is made to transport and even compute the values for those properties.

The default is all defined properties, as per vocabspec.

Behavior is undefined if you update or create with properties not in
the select list.

Note that SELECT A WHERE B="FOO" has to be done like:

db.where({b: 'foo'}).select('a')

NOT db.select('a').where({b: 'foo'}) because .where can't even see b,
because it wasn't passed through by .select('a')

call it db.produce ?

Make it part of the filter options, not really part of db.

=== [IDEA] db.join(n)

Returns a read-only dbview containing n-tuples where each position has each element in db.

For example, if db contains {a:1} and {a:2}:

then db.join(2) is
       {1:{a:1}, 2:{a:1}}
       {1:{a:1}, 2:{a:2}}
       {1:{a:2}, 2:{a:1}}
       {1:{a:2}, 2:{a:2}}

db.join(3) is

       {1:{a:1}, 2:{a:1}, 3:{a:1}}
       {1:{a:1}, 2:{a:1}, 3:{a:2}}
       ...
       {1:{a:2}, 2:{a:2}, 3:{a:2}}

This allows relational database joins to be expressed within the
datapages formalism.  Actually traversing the results of a join is not
recommended and might not be supported (an n-way join of a datapage
with k pages will have k^n pages).  Instead, the join should be
followed immediately by a .where, which can implement a more efficient
search.

For example, in SQL given tables LIKES (person, food) and FOODFROM (food, origin), the query SELECT person, origin WHERE LIKES.food = FOODFROM.food would be

db.join(2)
  .where({'1.isLIKE': true,
          '2.isFOODFROM': true,
          '1.food': {$valueOfProperty: '2.food'}})
  .select(['1.person', '2.origin'])          

(Consider making it .joinWhere(n, filterexpr, renames) to avoid issues.)

This can probably be done more cleanly as a virtual page rule:

 db.addVirtualPageRule({likes: 'person, food',
                        foodfrom: 'food, origin'},
                       'person, origin',
                        (likes, foodfrom)


 db.addVirtualPageRule('person, likesFoodFrom', 'person, food', 'food, origin', 
                       (likes, foodfrom) => {
                          if (likes.food === foodfrom.food) {
                             return {person: likes.person,
                                     likesFoodFrom: foodfrom.origin}
                          }
                       }

It'd be nice to have better filter exprs, like `{ food: {$wanted: true}, origin: {$exists: true} }`

We could do forward chaining just running that blindly, but for
backward chaining we'd want a lot more.   Maybe

 db.$exists = {$exists: true} // etc
 db.addVirtualPageRule({person: db.$exists, likesFoodFrom: db.$exists},
                       [{person: db.$exists,
                         food: db.$exists},
                        {food: {$eq: {$valueOfProperty: '0.food'}},
                         ... 

OR just a simple statement of === join fields.  Other relations are
less useful for optimizing.

 db.join(['food', 'food']) ....   that doesn't quite work, I expect.

== Media Pages

Some datapages have an attached digital media instance, such as a jpeg
image or an mp3 audio sample.  This attachment is handled efficiently
as a "blob", not part of the datapage itself.

Every media page has a mediaType property, which has the normal IANA
media type information, like 'image/jpeg'.  (Encoding...?)

The media instance data itself can be accessed via a streaming API:

  db.mediaReadStrean(page, options) returns a readable stream

  db.mediaWriteStream(page, mediaType, options) returns a writable stream

When end() is called on the writable stream , the mediaType will be
set and db.mediaReadStream will work.

Concurrency during writes is not allowed: betwen the time
mediaWriteStream is called and the stream's end() function is called,
other calls to either of these functions will return null.  In theory
we should track the open read streams as well.  Also, in theory, we
could just pause the non-winning readers and writers, rather than
returning null.   Tricky.

(When there's an attached webserver, .mediaURL should also be set)


== Vocabulary

Every dbview has a .vocab which is a [vocabspec](https://github.com/sandhawke/vocabspec) instance.


== Instance Types

Various useful classes, nearly all of which implement approx the same
dbview interface, in roughly increasing order of complexity:

=== Filestore: on disk, each page is its own file

=== [PLANNED] Cache: wrapper which caches some/all of the underlying db

=== [PLANNED] Multisource: wrapper for 1-write N-read dbs, appearing as one db

Wraps a db, also implementing .attach(dbN) for including other
read-only dbs.  Queries query them as well and merge the results.

Writes just go back to primary db.

BUT, depending on our delta model, etc, writes might APPEAR to
change the data, by blocking data from other sources.  That part's
not quite there yet.

==== db.include()

=== [IDEA] Accesscontrolled: gives a partial view of a db based on 'user' attributes

** parameterized by uid and a trusted authinfo db

=== [IDEA] Rulebase: computes virtual properties, virtual pages, and checks validity
** with accessControled allows sophisticated rules
** probably needs a way to run safe JS functions

start with backchainsubproperty and forwardchainsubproperty
then bcdatalog and fcdatalog
then bcHorn, probably

=== [IDEA] EqualityReasoner

Gives a view of the data where some obj's are "about" the same
thing, and so the data from one carries over to the other.  For
example:

```js
db.add({ name: "Alice", age: 30 })
db.add({ name: "Alice", hairColor: "dark" })
db.addKey('name')
db.forEach(x => {
    // x = { name: 'Alice', age:30, hairColor: 'dark' }
})
```

uhhhhh.   Can't really be done with current API

Except, if N pages can be merged, the db creates a new page, and
db.mergedInto(p1, pmergerd)
db.mergedInto(p2, pmergerd)

BUT that would still show through p1 and p2

```js
db.filter({__smooshedIfPossible: true}).forEach( ... )

db.on('replace', ... )   or 'merge'N
...  p1 and p2 go away, and you get a new one?
```

THIS SEEMS OBSCURE, but actually, it's essential to making
decentralization work!

Do we need to change dbview?

? can you compare with ===

I think so, because of pointers / graphs

==== db.addKey (prop)

==== db.isSameSubjectAs (a, b)

==== db.makeSameSubjectAs (a, b)

==== db.isSamePageAs (a, b)

==== db.makeSameSubjectAs (a, b)

==== db.refmod(property, type)

Set the "reference mode" for given property to be given type, which is one of: page, subject, ...

Needs to be known for every property....    Do we default to 'subject' unless you say 'page'

=== [IDEA] vocabularyMapped view

basically run vocabspec convert on all data going in or out

easy to test inmem

might be used by rule engine to recognize its own vocabulary without
conflicting with anyone elses.   